from django.core.management.base import BaseCommand
from django.db import transaction
from decimal import Decimal
import random

# ── Import your actual app models below ──────────────────────────────────────
# Replace 'your_app' with your real Django app name
from products.models import Category, Product
# ─────────────────────────────────────────────────────────────────────────────


# ── 10 Categories with 50 products each ──────────────────────────────────────

SEED_DATA = {
    "Electronics": [
        ("Wireless Bluetooth Headphones",    "Over-ear noise-cancelling headphones with 30h battery.",        4999.99, True),
        ("USB-C Fast Charger 65W",           "GaN charger supporting PD 3.0 for laptops and phones.",         1299.00, True),
        ("Mechanical Keyboard TKL",          "Tenkeyless RGB keyboard with Cherry MX Red switches.",          3499.00, True),
        ("4K Webcam 60fps",                  "Wide-angle webcam with built-in ring light and mic.",           2799.00, True),
        ("Portable SSD 1TB",                 "NVMe portable drive with 1050 MB/s read speed.",               5999.00, True),
        ("Smart LED Desk Lamp",              "Touch-dimming lamp with USB-A charging port.",                   899.00, True),
        ("Wireless Mouse Ergonomic",         "Silent clicks, 6-button ergonomic design, 18-month battery.",  1499.00, True),
        ("HDMI 2.1 Cable 2m",                "8K@60Hz certified cable with braided nylon jacket.",             349.00, True),
        ("Laptop Cooling Pad",               "Dual 140mm fans with adjustable height and RGB.",               999.00, True),
        ("Bluetooth Numpad",                 "Rechargeable wireless numpad compatible with all OSes.",         749.00, True),
        ("Smart Plug Wi-Fi",                 "Energy monitoring smart plug compatible with Alexa & Google.",   499.00, True),
        ("Mini PC Intel N100",               "Fanless mini PC with 16 GB RAM and 512 GB SSD.",              14999.00, True),
        ("USB Hub 10-Port",                  "Powered USB 3.0 hub with individual on/off switches.",        1199.00, True),
        ("E-Ink Monitor 13in",               "Paper-like display, eye-safe for reading and coding.",        19999.00, False),
        ("VR Headset Standalone",            "6DoF standalone headset with 128 GB storage.",               34999.00, True),
        ("Action Camera 4K",                 "Waterproof up to 10 m, 170° wide-angle lens.",                5499.00, True),
        ("Solar Power Bank 20000mAh",        "Dual solar panels with 18W fast charging.",                   2499.00, True),
        ("Smart Doorbell Camera",            "1080p video, two-way audio, night vision.",                   3999.00, True),
        ("Fingerprint USB Drive 128GB",      "Hardware-encrypted drive with biometric lock.",               2199.00, True),
        ("Graphic Tablet A5",                "8192 pressure levels, battery-free stylus, 8 express keys.",  3299.00, True),
        ("Noise-Cancelling Earbuds",         "ANC earbuds with 8h playtime + 24h case.",                   2999.00, True),
        ("Smart IR Remote Hub",              "Control all IR devices via smartphone app.",                    799.00, True),
        ("Portable Projector Mini",          "500 ANSI lumens, HDMI + Wi-Fi, built-in speaker.",            8999.00, True),
        ("RGB LED Strip 5m",                 "Wi-Fi controlled, 16M colours, music sync mode.",              1099.00, True),
        ("Wireless Charging Pad 15W",        "Qi2 certified pad with foreign object detection.",             999.00, True),
        ("UPS 600VA",                        "Line-interactive UPS with AVR for desktop PCs.",              4499.00, True),
        ("Thermal Printer Mini",             "Bluetooth receipt printer, no ink needed, 58mm paper.",       1799.00, True),
        ("Digital Multimeter Auto",          "True-RMS multimeter with NCV detector and backlight.",        1249.00, True),
        ("Soldering Station 60W",            "Temperature-controlled station with 5 tip set.",              1999.00, True),
        ("Raspberry Pi 5 4GB",               "Latest SBC with PCIe, dual 4K display support.",             5499.00, False),
        ("Arduino Mega Starter Kit",         "Complete kit with 200+ components and project guide.",        2799.00, True),
        ("Oscilloscope 2CH 100MHz",          "Handheld scope with FFT analysis and USB storage.",          12999.00, True),
        ("Wi-Fi Range Extender AC1200",      "Dual-band extender with MU-MIMO and 4 antennas.",            1599.00, True),
        ("Network Switch 8-Port Gigabit",    "Unmanaged Gigabit switch with plug-and-play setup.",         1299.00, True),
        ("Outdoor Security Camera 4K",       "PoE camera with colour night vision and AI detection.",      5999.00, True),
        ("Drone Camera 4K GPS",              "Foldable drone, 30-min flight, 3-axis gimbal.",             24999.00, True),
        ("Smart Scale Body Composition",     "14-metric Bluetooth scale syncs with health apps.",          1499.00, True),
        ("Car OBD2 Bluetooth Scanner",       "Read/clear engine codes via smartphone.",                     799.00, True),
        ("Handheld Game Console",            "Android-based 3.5in IPS display, dual joysticks.",           4999.00, True),
        ("LED Monitor 27in IPS",             "1440p 165Hz, 1ms MPRT, HDR400 certified.",                  17999.00, True),
        ("Curved Monitor 34in UW",           "3440×1440 ultrawide VA panel, 144Hz, 1ms.",                 29999.00, False),
        ("Wireless HDMI Transmitter",        "60GHz wireless display kit up to 10 m, 4K@30Hz.",           5999.00, True),
        ("USB Microphone Cardioid",          "Studio-quality condenser mic with mute button.",             2299.00, True),
        ("Smart TV Box 4K",                  "Android 13 TV stick with Wi-Fi 6 and BT 5.2.",              2499.00, True),
        ("PD Power Strip 6-Outlet",          "100W USB-C PD + 3 USB-A ports, surge protected.",           1799.00, True),
        ("Laptop Stand Aluminium",           "Ergonomic riser, foldable, fits 10–17in laptops.",           1199.00, True),
        ("Barcode Scanner 2D USB",           "Omnidirectional 2D QR and barcode reader.",                  1899.00, True),
        ("Label Printer Wireless",           "Bluetooth label maker, 180 dpi, iOS/Android app.",          3299.00, True),
        ("Thermal Camera Module",            "256×192 IR sensor, USB-C, for smartphone.",                  6999.00, False),
        ("Smart Glasses BT Audio",           "Open-ear audio glasses with built-in mic.",                  8999.00, True),
    ],

    "Fashion": [
        ("Men's Slim Chinos Navy",           "Stretch cotton blend chinos with tapered fit.",              1799.00, True),
        ("Women's Wrap Dress Floral",        "Lightweight rayon wrap dress, midi length.",                 1599.00, True),
        ("Unisex Oversized Hoodie",          "400 GSM fleece hoodie in 12 colours.",                       1999.00, True),
        ("Leather Belt Brown 38mm",          "Full-grain leather with brass pin buckle.",                   899.00, True),
        ("Canvas Tote Bag Natural",          "Heavyweight 12 oz canvas, reinforced straps.",               599.00, True),
        ("Men's Oxford Shirt White",         "100% Egyptian cotton, button-down collar.",                  1299.00, True),
        ("Women's High-Waist Leggings",      "4-way stretch moisture-wicking fabric.",                     999.00, True),
        ("Aviator Sunglasses Polarised",     "UV400 polarised lenses, stainless steel frame.",             1499.00, True),
        ("Beanie Wool Ribbed",               "Merino wool beanie, one size fits all.",                     699.00, True),
        ("Sling Bag Crossbody",              "Vegan leather sling with USB charging port.",               1199.00, True),
        ("Men's Jogger Pants Grey",          "Slim-fit French terry joggers with zip pockets.",            1099.00, True),
        ("Women's Blazer Oversized",         "Structured double-button blazer, office-ready.",             2499.00, True),
        ("Graphic Tee Vintage Wash",         "Ring-spun cotton tee with distressed graphic.",              699.00, True),
        ("Snapback Cap Embroidered",         "6-panel structured cap with flat brim.",                     799.00, True),
        ("Ankle Boots Chelsea Women",        "Elastic-sided chelsea boots with block heel.",               2999.00, True),
        ("Men's Derby Shoes Tan",            "Goodyear welted sole, genuine leather upper.",               3999.00, True),
        ("Sports Bra Medium Support",        "Racerback style with removable padding.",                     899.00, True),
        ("Scarf Cashmere Blend Plaid",       "28% cashmere blend, 180×30 cm.",                            1299.00, True),
        ("Women's Mom Jeans Light Wash",     "High-rise relaxed-fit denim with raw hem.",                 1899.00, True),
        ("Men's Quarter-Zip Pullover",       "Anti-pill fleece with contrast zip.",                       1599.00, True),
        ("Slip-On Loafers Canvas",           "EVA sole, memory foam insole, 6 colours.",                   999.00, True),
        ("Trench Coat Women's Beige",        "Double-breasted, belted trench with epaulettes.",            4999.00, True),
        ("Bucket Hat Cotton Twill",          "Reversible bucket hat, UPF 50+.",                            699.00, True),
        ("Wallet Bifold Minimalist",         "Slim RFID-blocking bifold, 8 card slots.",                   799.00, True),
        ("Running Shorts 5in Lined",         "Lightweight with inner compression liner.",                   799.00, True),
        ("Women's Puffer Vest",              "Lightweight down-fill vest, packable.",                     1799.00, True),
        ("Men's Linen Shorts Khaki",         "Relaxed-fit linen shorts with elastic waist.",               999.00, True),
        ("Tie Silk Navy Stripe",             "100% silk tie, 8 cm blade, hand-finished.",                  1499.00, True),
        ("Rash Guard Long Sleeve",           "UPF 50+, flatlock seams, quick-dry.",                       1099.00, True),
        ("Formal Waistcoat Charcoal",        "Single-breasted 5-button waistcoat.",                       1799.00, True),
        ("Women's Midi Skirt Satin",         "Bias-cut satin midi skirt with side slit.",                 1399.00, True),
        ("Crew Neck Sweatshirt White",       "Garment-dyed 380 GSM cotton sweatshirt.",                   1499.00, True),
        ("Compression Socks 3-Pack",         "Graduated compression, 15–20 mmHg.",                        699.00, True),
        ("Denim Jacket Washed Blue",         "Classic trucker jacket with distressed finish.",             1999.00, True),
        ("Bralette Lace Trim",               "Adjustable straps, unlined, 5 colours.",                     799.00, True),
        ("Men's Swim Trunks Printed",        "Quick-dry fabric, mesh lining, 7in inseam.",                 899.00, True),
        ("Maxi Dress Boho Tiered",           "Crinkle fabric, smocked bodice, adjustable straps.",        1699.00, True),
        ("Polo Shirt Pique Men's",           "Classic fit, embroidered logo, 8 colours.",                 1199.00, True),
        ("Wedge Sandals Women's",            "Espadrille wedge, ankle strap, cork platform.",             1999.00, True),
        ("Cargo Pants Men's Olive",          "Relaxed fit with 8 pockets, ripstop fabric.",               1799.00, True),
        ("Turtleneck Knit Women's",          "Ribbed knit turtleneck in earth tones.",                    1299.00, True),
        ("Slim Tie Wool Grey",               "7 cm blade slim tie, pure wool.",                           1099.00, True),
        ("Flip Flops EVA Unisex",            "Anatomic EVA footbed with grip sole.",                       499.00, True),
        ("Bomber Jacket Men's Black",        "MA-1 style, ribbed cuffs and hem.",                         2999.00, True),
        ("Culottes Women's Linen",           "Wide-leg cropped pants in linen blend.",                    1199.00, True),
        ("Gloves Touch Screen Knit",         "Conductive fingertips, machine washable.",                   499.00, True),
        ("Bodycon Dress Ribbed",             "Stretch ribbed bodycon dress, knee-length.",                 999.00, True),
        ("Suspenders Elastic Men's",         "Y-back leather-end suspenders.",                            699.00, True),
        ("Track Jacket Retro Zip",           "Tricot polyester, contrast stripe, full zip.",              1799.00, True),
        ("Oxford Shoes Women's Block",       "Lace-up oxford with chunky block heel.",                    2299.00, True),
    ],

    "Home & Kitchen": [
        ("Cast Iron Skillet 10in",           "Pre-seasoned cast iron, oven-safe to 260°C.",               1999.00, True),
        ("Air Fryer 5.5L Digital",           "8 presets, rapid air technology, non-stick basket.",        4999.00, True),
        ("Stainless Steel Mixing Bowls Set", "Set of 5 nesting bowls with lids, non-slip base.",         1799.00, True),
        ("Bamboo Cutting Board Large",       "Anti-bacterial bamboo with juice groove.",                   899.00, True),
        ("Vacuum Storage Bags 10-Pack",      "Space-saver bags for seasonal clothing.",                    799.00, True),
        ("Silicone Baking Mat 2-Pack",       "Non-stick half-sheet mat, reusable, BPA-free.",             599.00, True),
        ("Instant Pot Duo 6Qt",              "7-in-1 multi-cooker, 13 smart programs.",                   7999.00, True),
        ("French Press Coffee Maker",        "Borosilicate glass + stainless double-wall press.",         1299.00, True),
        ("Knife Sharpener Electric",         "3-stage diamond abrasive sharpener.",                        999.00, True),
        ("Under-Sink Water Filter",          "3-stage filtration, 10000 L cartridge life.",               3499.00, True),
        ("Compost Bin 3L Countertop",        "Odour-free charcoal filter, stainless lid.",                 799.00, True),
        ("Non-Stick Pan Set 3pc",            "Ceramic coating, induction-compatible.",                    2499.00, True),
        ("Kitchen Scale Digital 5kg",        "0.1g precision, tare function, LCD display.",               799.00, True),
        ("Stainless Spice Rack 12 Jars",     "Magnetic wall-mount rack with labelled jars.",              1199.00, True),
        ("Toaster 4-Slice Stainless",        "6 browning levels, defrost/reheat/cancel.",                 1799.00, True),
        ("Hand Blender 800W",                "Turbo mode, 8 speeds, attachments included.",               1499.00, True),
        ("Wine Rack Freestanding 24",        "Metal freestanding rack for 24 bottles.",                   1999.00, True),
        ("Drawer Organiser Set 14pc",        "Expandable bamboo drawer dividers.",                         999.00, True),
        ("Over-Door Pantry Organiser",       "4-tier adjustable steel pantry hanger.",                   1299.00, True),
        ("Dish Drying Rack Stainless",       "2-tier rack with drainage tray and utensil holder.",       1499.00, True),
        ("Instant Read Thermometer",         "3-second read, ±1°C accuracy, auto-off.",                   699.00, True),
        ("Reusable Beeswax Wraps 5pc",       "Biodegradable food wrap alternative.",                      699.00, True),
        ("Slow Cooker 6Qt Oval",             "3 heat settings, dishwasher-safe stoneware.",               2999.00, True),
        ("Glass Meal Prep Containers 5pc",   "1L borosilicate glass with snap-lock lids.",               1299.00, True),
        ("Pasta Maker Machine Manual",       "Adjustable 9-thickness settings, stainless rollers.",      2499.00, True),
        ("Bread Box Bamboo",                 "Keeps bread fresh 3× longer, ventilated lid.",              1099.00, True),
        ("Mandoline Slicer Adjustable",      "5-blade mandoline with safety guard.",                       999.00, True),
        ("Magnetic Knife Strip 40cm",        "Wooden magnetic bar for 8+ knives.",                         799.00, True),
        ("Silicone Utensil Set 6pc",         "Heat-resistant to 230°C, dishwasher-safe.",                 799.00, True),
        ("Tea Kettle Stovetop 1.8L",         "Stainless steel whistling kettle, all hobs.",               1199.00, True),
        ("Electric Griddle 35×25cm",         "Non-stick coating, drip tray, adjustable thermostat.",     2499.00, True),
        ("Coffee Grinder Burr Electric",     "Conical burr, 18 grind settings, 200g hopper.",            3499.00, True),
        ("Bento Box Stainless 3-Tier",       "Leak-proof stacked lunch box with carry bag.",               999.00, True),
        ("Herb Scissors 5-Blade",            "Stainless 5-blade herb cutter with cover.",                  499.00, True),
        ("Pressure Cooker Stovetop 6L",      "18/10 stainless, dual pressure settings.",                 3499.00, True),
        ("Pot Rack Ceiling Mounted",         "Iron ceiling pot hanger, holds 12 pots.",                  4999.00, False),
        ("Oven Mitts Silicone Pair",         "Heat-resistant to 260°C, non-slip grip.",                   599.00, True),
        ("Dish Soap Dispenser Pump",         "Stainless steel countertop soap pump, 600 ml.",             699.00, True),
        ("Salad Spinner Large 5L",           "One-touch brake button, BPA-free bowl.",                    1299.00, True),
        ("Avocado Slicer 3-in-1",            "Split, pit, and slice avocados safely.",                    399.00, True),
        ("Mortar and Pestle Granite",        "Rough-interior granite set, 300ml capacity.",               1199.00, True),
        ("Ice Cube Tray Silicone 2pc",       "Large 4×4 cube trays with dust-proof lid.",                 499.00, True),
        ("Pot Holder Quilted Cotton 4pc",    "Machine-washable, double-layered.",                          399.00, True),
        ("Tofu Press Stainless",             "Two-plate tofu press, adjustable spring.",                   799.00, True),
        ("Magnetic Fridge Organiser 3pc",    "Side-mount fridge organisers for bottles.",                  699.00, True),
        ("Spoon Rest Ceramic",               "Hand-painted ceramic spoon rest, dishwasher-safe.",         399.00, True),
        ("Cookie Cutters Set 50pc",          "Stainless steel cutter set with storage case.",              799.00, True),
        ("Egg Cooker 7-Egg Electric",        "Auto-off, hard/soft/poached/omelette mode.",                999.00, True),
        ("Wok 36cm Carbon Steel",            "Hammered carbon steel, flat bottom, wooden handle.",       1799.00, True),
        ("Jar Opener 5-in-1",                "Opens jar, bottle, and can lids with ease.",                 499.00, True),
    ],

    "Books": [
        ("Atomic Habits – Clear",            "Proven system for building good and breaking bad habits.",  499.00, True),
        ("The Psychology of Money",          "Timeless lessons on wealth, greed, and happiness.",         399.00, True),
        ("Deep Work – Cal Newport",          "Rules for focused success in a distracted world.",          449.00, True),
        ("Sapiens – Harari",                 "A brief history of humankind across millennia.",            549.00, True),
        ("The Alchemist – Coelho",           "Classic tale of following your dreams.",                    299.00, True),
        ("Think and Grow Rich",              "Timeless principles of achievement and wealth.",             349.00, True),
        ("Zero to One – Thiel",              "Notes on startups and building the future.",                499.00, True),
        ("Ikigai – Garcia & Miralles",       "The Japanese secret to a long and happy life.",             349.00, True),
        ("Rich Dad Poor Dad",                "What the rich teach their kids about money.",               399.00, True),
        ("The 4-Hour Work Week",             "Escape 9–5, live anywhere, join the new rich.",             449.00, True),
        ("Dune – Frank Herbert",             "Epic science fiction set on desert planet Arrakis.",        499.00, True),
        ("1984 – George Orwell",             "Dystopian vision of a totalitarian surveillance state.",    299.00, True),
        ("Brave New World – Huxley",         "Society controlled by technology and pleasure.",            299.00, True),
        ("The Great Gatsby – Fitzgerald",    "Jazz Age story of ambition and the American dream.",        299.00, True),
        ("Crime and Punishment",             "Dostoevsky's masterpiece on guilt and redemption.",         499.00, True),
        ("To Kill a Mockingbird",            "Harper Lee's Pulitzer-winning story of justice.",           349.00, True),
        ("The Midnight Library – Haig",      "A novel between life and death, full of possibilities.",   449.00, True),
        ("Project Hail Mary – Weir",         "A lone astronaut races to save Earth.",                    549.00, True),
        ("The Silent Patient",               "Psychological thriller with a shocking twist.",             399.00, True),
        ("It Ends with Us – Hoover",         "Powerful story about love and difficult choices.",          399.00, True),
        ("Educated – Tara Westover",         "A memoir of self-invention and education.",                 499.00, True),
        ("Becoming – Michelle Obama",        "Memoir of the former US First Lady.",                       599.00, True),
        ("The Body – Bill Bryson",           "A guide to the human body and its wonders.",               499.00, True),
        ("Brief Answers Big Questions",      "Stephen Hawking on science and humanity.",                  549.00, True),
        ("Thinking Fast and Slow",           "Kahneman's exploration of two systems of thought.",         549.00, True),
        ("Never Split the Difference",       "FBI negotiator's guide to high-stakes talks.",              499.00, True),
        ("The Lean Startup – Ries",          "How today's entrepreneurs use continuous innovation.",      499.00, True),
        ("Good to Great – Collins",          "Why some companies make the leap and others don't.",        549.00, True),
        ("The Art of War – Sun Tzu",         "Ancient Chinese treatise on strategy.",                    249.00, True),
        ("Man's Search for Meaning",         "Frankl's account of Holocaust survival and purpose.",      399.00, True),
        ("The Power of Now – Tolle",         "Guide to spiritual enlightenment and presence.",            399.00, True),
        ("Start With Why – Sinek",           "How great leaders inspire action.",                         449.00, True),
        ("Extreme Ownership – Willink",      "Navy SEALs on leadership and accountability.",             499.00, True),
        ("Can't Hurt Me – Goggins",          "Master your mind and defy the odds.",                      499.00, True),
        ("The 5 AM Club – Sharma",           "Own your morning, elevate your life.",                     399.00, True),
        ("Harry Potter Box Set 1–7",         "Complete paperback set of J.K. Rowling's series.",        2499.00, True),
        ("Game of Thrones 5-Book Set",       "George R.R. Martin's Song of Ice and Fire.",             2999.00, True),
        ("The Hitchhiker's Guide Galaxy",    "Douglas Adams' comedic sci-fi classic.",                   349.00, True),
        ("Sherlock Holmes Complete",         "All 60 stories by Arthur Conan Doyle.",                    699.00, True),
        ("Agatha Christie Omnibus",          "30 mystery novels in one volume.",                         999.00, True),
        ("Python Crash Course 3rd Ed",       "Hands-on introduction to programming with Python.",        799.00, True),
        ("Clean Code – Robert Martin",       "A handbook of agile software craftsmanship.",              799.00, True),
        ("Designing Data-Intensive Apps",    "Principles behind reliable, scalable systems.",           1099.00, True),
        ("The Pragmatic Programmer",         "From journeyman to master developer.",                     899.00, True),
        ("CLRS – Introduction Algorithms",   "Comprehensive introduction to algorithms.",               1299.00, True),
        ("Hooked – Nir Eyal",                "How to build habit-forming products.",                     499.00, True),
        ("Influence – Robert Cialdini",      "The psychology of persuasion.",                            499.00, True),
        ("The Innovator's Dilemma",          "Why great companies can fail when markets change.",        549.00, True),
        ("Purple Cow – Seth Godin",          "Transform your business by being remarkable.",             449.00, True),
        ("Made to Stick – Heath Bros",       "Why some ideas survive and others die.",                   449.00, True),
    ],

    "Sports & Outdoors": [
        ("Yoga Mat TPE 6mm",                 "Non-slip TPE mat with alignment lines, 183×61 cm.",        1499.00, True),
        ("Resistance Bands Set 5pc",         "Loop bands: 5–150 lb, colour-coded.",                      799.00, True),
        ("Adjustable Dumbbell 24kg",         "Click-adjust from 2 kg to 24 kg in 2 kg steps.",          8999.00, True),
        ("Jump Rope Speed Cable",            "Steel cable rope with ball-bearing handles.",               599.00, True),
        ("Foam Roller High Density",         "EPP foam roller for myofascial release, 90 cm.",           799.00, True),
        ("Pull-Up Bar Doorframe",            "No-screw doorframe bar, 100–150 cm width.",               1299.00, True),
        ("Kettlebell Cast Iron 16kg",        "Single-piece cast iron, flat base, 16 kg.",               1999.00, True),
        ("Gym Gloves Padded",                "Full palm padding with wrist wrap support.",               699.00, True),
        ("Protein Shaker BPA-Free 700ml",    "Leak-proof with stainless whisk ball.",                   399.00, True),
        ("Running Belt Hydration",           "Adjustable belt with two 250 ml soft flasks.",             999.00, True),
        ("Trekking Poles Foldable",          "Carbon-fibre tri-fold poles, 100 cm pack.",              2499.00, True),
        ("Sleeping Bag 0°C Mummy",           "Down fill, 2-way zip, compression sack.",                 3999.00, True),
        ("Camping Lantern Rechargeable",     "360° LED, 3 brightness modes, magnetic base.",             899.00, True),
        ("Waterproof Dry Bag 20L",           "Roll-top PVC dry bag for kayaking/hiking.",                799.00, True),
        ("Multitool Pocket 18-in-1",         "Stainless steel plier-based multi-tool.",                 1499.00, True),
        ("Carabiner Locking D-Shape",        "UIAA-certified aluminium, 24 kN gate.",                   699.00, True),
        ("Hydration Bladder 3L",             "BPA-free reservoir with bite-valve tube.",                  799.00, True),
        ("Headlamp LED 400 Lumens",          "Rechargeable USB-C, red light mode, 40m beam.",            999.00, True),
        ("Swim Goggles Anti-Fog",            "UV protection, wide-view lens, adult fit.",                 599.00, True),
        ("Tennis Racket Carbon 300g",        "Pre-strung carbon frame, mid+ head size.",                2499.00, True),
        ("Badminton Set 4 Rackets",          "2 rackets, 3 shuttlecocks, carrying bag.",                 999.00, True),
        ("Cricket Batting Gloves",           "Leather palm, SBR padding, right-hand.",                  1299.00, True),
        ("Football Size 5 FIFA",             "32-panel thermally bonded match ball.",                   1499.00, True),
        ("Basketball Outdoor Grip",          "Rubber outdoor ball, deep channel design, sz 7.",         1299.00, True),
        ("Table Tennis Paddle Pro",          "Speed 90, spin 85, 2.0mm rubber thickness.",               999.00, True),
        ("Cycling Helmet MIPS",              "MIPS liner, 26 vents, dial fit system.",                  2999.00, True),
        ("Knee Pads Volleyball Pair",        "EVA foam padding, moisture-wicking sleeve.",               699.00, True),
        ("Boxing Gloves 12oz",               "Genuine leather shell, multi-layer foam.",                 2499.00, True),
        ("Punching Bag 40kg Filled",         "Synthetic leather, chain & bracket included.",             6999.00, True),
        ("Archery Recurve Set Beginner",     "20 lb draw, 4 arrows, finger guard.",                    2999.00, True),
        ("Fitness Tracker Band",             "24/7 heart rate, SpO2, 7-day battery.",                   1999.00, True),
        ("Yoga Block Cork 2pc",              "High-density cork block pair, 22×14×8 cm.",               799.00, True),
        ("Skipping Board Balance",           "Wobble balance board, 40 cm circle.",                     1499.00, True),
        ("Pull Buoy Swim Float",             "EVA pull buoy for leg isolation drills.",                   399.00, True),
        ("Weight Lifting Belt Leather",      "6in tapered leather belt, double prong.",                 1999.00, True),
        ("Resistance Tube Heavy 40kg",       "Fabric-covered tube with handles and anchors.",            799.00, True),
        ("Ankle Weights 2kg Pair",           "Adjustable sand-fill ankle/wrist weights.",               699.00, True),
        ("Running Cap DryFit",               "Lightweight moisture-wicking with 360° vent.",             599.00, True),
        ("Gym Bag Duffel 45L",               "Wet compartment, shoe pocket, padded strap.",             1699.00, True),
        ("Skates Inline Aggressive",         "80mm wheels, ABEC-7 bearings, lace+buckle.",             4999.00, True),
        ("Snorkel Set Adult",                "Dry-top snorkel, tempered glass mask, fins.",             1999.00, True),
        ("Kayak Paddle Aluminium",           "2-piece adjustable aluminium paddle, 220 cm.",            2499.00, True),
        ("Climbing Shoes Beginner",          "Flat last, hook-and-loop strap, rubber rand.",            3499.00, True),
        ("Yoga Strap 8ft Cotton",            "D-ring strap in 10 colours, non-elastic.",                 399.00, True),
        ("Ab Roller Double Wheel",           "Wide-base double wheel with knee pad.",                    599.00, True),
        ("Agility Ladder 6m Nylon",          "20-rung ladder with stakes and carry bag.",                799.00, True),
        ("Handball Team Ball Size 3",        "IHF-approved PU leather, indoor match ball.",             1299.00, True),
        ("Swimming Board Kick Float",        "EVA foam kickboard, hydrodynamic shape.",                   499.00, True),
        ("Power Rack Cage Home Gym",         "Heavy-duty 4-post rack, J-hooks, dip bars.",            19999.00, False),
        ("Medicine Ball 5kg Rubber",         "Dead-bounce rubber med ball with texture.",                999.00, True),
    ],

    "Beauty & Personal Care": [
        ("Vitamin C Serum 30ml",             "15% L-ascorbic acid, ferulic acid, brightening.",         1299.00, True),
        ("Hyaluronic Acid Moisturiser",      "Multi-weight HA, ceramide complex, 50ml.",               1199.00, True),
        ("Retinol Night Cream 50ml",         "0.3% encapsulated retinol, bakuchiol blend.",             1499.00, True),
        ("Niacinamide 10% Toner",            "Pore-refining toner with zinc PCA.",                      799.00, True),
        ("Sunscreen SPF 50+ PA++++",         "Invisible watery gel, no white cast, 50ml.",              999.00, True),
        ("Micellar Cleansing Water 400ml",   "Triple action, removes makeup + SPF.",                    799.00, True),
        ("Jade Roller & Gua Sha Set",        "Real jade facial roller with gua sha stone.",             699.00, True),
        ("Electric Face Cleanser Sonic",     "3 modes, IPX7 waterproof, silicone head.",               2999.00, True),
        ("Clay Mask Kaolin 100ml",           "Deep pore-cleansing mask with tea tree oil.",             599.00, True),
        ("Lip Balm SPF 30 Set 6pc",          "Tinted SPF lip balms in 6 shades.",                      699.00, True),
        ("Beard Oil 30ml Jojoba",            "Jojoba + argan blend, woodsy cedar scent.",              699.00, True),
        ("Safety Razor Double Edge",         "Butterfly-open stainless DE razor.",                     1299.00, True),
        ("Shaving Cream Sensitive 150g",     "Aloe vera & chamomile shaving cream.",                    499.00, True),
        ("Hair Growth Serum 50ml",           "Redensyl 3%, caffeine, biotin complex.",                 1499.00, True),
        ("Dry Shampoo 200ml Invisible",      "No residue, volumising oat-based formula.",               699.00, True),
        ("Argan Oil Hair Mask 200ml",        "Deep conditioning mask for colour-treated hair.",         899.00, True),
        ("Comb Set Anti-Static 5pc",         "Wide and fine tooth combs with round brush.",             499.00, True),
        ("Electric Toothbrush Sonic",        "40000 strokes/min, 3 modes, 4 brush heads.",            2999.00, True),
        ("Teeth Whitening Strips 14-Pack",   "14-day non-sensitive enamel-safe strips.",               999.00, True),
        ("Tongue Cleaner Copper 2pc",        "Ayurvedic copper tongue scraper.",                        299.00, True),
        ("Perfume Pocket Atomiser 5ml",      "Refillable travel-size perfume atomiser.",                399.00, True),
        ("Essential Oil Set 6×10ml",         "Lavender, tea tree, eucalyptus + 3 more.",               999.00, True),
        ("Body Scrub Coffee 200g",           "Cold-press coffee, coconut oil body scrub.",              699.00, True),
        ("Loofah Sponge 3-Pack Natural",     "Organic dried loofah, exfoliating bath sponge.",         399.00, True),
        ("Nail File Set 12pc",               "Glass and metal files in various grits.",                  349.00, True),
        ("Eyebrow Razor 3pc",                "Facial dermaplaning razor for precise shaping.",          299.00, True),
        ("Under Eye Patches 60pc",           "Hydrogel patches with collagen and caffeine.",            899.00, True),
        ("Eyelash Curler Pro",               "Hinged pad curler with replaceable pad set.",             499.00, True),
        ("Facial Ice Roller",                "Stainless steel roller for puffiness reduction.",         799.00, True),
        ("Body Butter Shea 200ml",           "Raw shea + cocoa body butter, unscented.",               799.00, True),
        ("Makeup Brush Set 12pc",            "Synthetic fibre, rose-gold ferrule, 12 brushes.",        1299.00, True),
        ("Blending Sponge 3pc",              "Latex-free teardrop sponge for seamless blends.",         499.00, True),
        ("Micellar Lip Scrub Sugar",         "Exfoliating vanilla sugar lip scrub, 15ml.",             399.00, True),
        ("Scalp Massager Shampoo Brush",     "Soft silicone bristles for scalp stimulation.",          449.00, True),
        ("Pore Strips Nose 20pc",            "Charcoal-infused blackhead removal strips.",             499.00, True),
        ("Sunscreen Stick SPF 50",           "Portable twist-up sun stick for face, 20g.",             699.00, True),
        ("Rosehip Facial Oil 30ml",          "100% organic cold-pressed rosehip oil.",                  899.00, True),
        ("Aloe Vera Gel Pure 250g",          "99% aloe vera gel, alcohol-free, cooling.",              499.00, True),
        ("Bio Oil Multiuse 60ml",            "Specialist skincare for scars and stretch marks.",        899.00, True),
        ("Bath Bomb Set 12pc",               "Fizzing bombs with shea, cocoa, and florals.",           799.00, True),
        ("Compact Mirror LED",               "360° foldable mirror with 3-colour LED ring.",          1299.00, True),
        ("Epilator Cordless 7-in-1",         "Wet/dry epilator with shaving head & trimmer.",         2999.00, True),
        ("Neck Massager EMS Wireless",       "EMS pulse neck massager with heat, 15 modes.",          2499.00, True),
        ("Blackhead Remover Vacuum",         "4 suction heads, USB rechargeable.",                    1499.00, True),
        ("Collagen Face Mask 10pc",          "Deep-hydration sheet masks with collagen.",              899.00, True),
        ("Overnight Lip Mask 15g",           "Honey + vitamin E lip sleeping mask.",                   499.00, True),
        ("Setting Spray Matte 100ml",        "Long-wear matte setting spray.",                         799.00, True),
        ("SPF Lip Gloss Set 4pc",            "Sheer tinted gloss with SPF 20.",                        699.00, True),
        ("Roll-On Deodorant Sensitive",      "48h protection, aluminium-free, vegan.",                 399.00, True),
        ("Facial Steamer Portable",          "Nano ionic steam for deep cleansing.",                  2499.00, True),
    ],

    "Toys & Games": [
        ("LEGO Classic Brick Set 1000pc",    "Open-ended creative building bricks, 8+.",              2999.00, True),
        ("Remote Control Car Off-Road",      "1:16 scale 4WD RC car, 30 km/h, 2.4 GHz.",             2499.00, True),
        ("Play-Doh Mega Set 36 Cans",        "36 non-toxic play dough colours with tools.",           1499.00, True),
        ("Monopoly Classic Board Game",      "The original property trading family game.",             999.00, True),
        ("Chess Set Wooden 40cm",            "Hand-carved pieces with storage drawer.",               1799.00, True),
        ("Uno Card Game 112 Cards",          "Classic colour-matching card game for all ages.",        399.00, True),
        ("Jenga Giant Outdoor",              "Oversized 54-block tumbling tower game.",               2999.00, True),
        ("Scrabble Deluxe Rotating Board",   "Rotating board with locking tiles.",                   1299.00, True),
        ("Rubik's Cube 3×3 Speed",           "Smooth-turning speedcube with UV coating.",             499.00, True),
        ("Jigsaw Puzzle 1000pc Landscape",   "Premium puzzle art of mountain landscape.",             699.00, True),
        ("Catan Board Game Base Set",        "Strategy game of trading and settlement.",             2499.00, True),
        ("Ticket to Ride Europe",            "Cross-Europe railway adventure game.",                  2999.00, True),
        ("Dixit Board Game",                 "Imaginative storytelling card game, 3–6 players.",     2499.00, True),
        ("Exploding Kittens 2-Pack",         "Strategic Russian roulette card game.",                 1199.00, True),
        ("Codenames Board Game",             "Word-guessing team game for parties.",                  1799.00, True),
        ("Slime Making Kit 30pc",            "DIY slime with glitter, foam beads, tools.",           799.00, True),
        ("Kinetic Sand 2kg Set",             "Mouldable magnetic sand with moulds.",                 1299.00, True),
        ("Soft Foam Bullet Blaster",         "Manual pump blaster, 24 foam darts.",                  999.00, True),
        ("Water Balloon Kit 500pc",          "Self-sealing water balloons for summer.",               599.00, True),
        ("Fidget Cube Desk Toy",             "6-sided sensory cube with click/spin/slide.",           349.00, True),
        ("Wooden Blocks 100pc Rainbow",      "Natural wood stacking blocks, non-toxic paint.",       1499.00, True),
        ("Baby Musical Xylophone",           "8-note wooden xylophone with mallets.",                 599.00, True),
        ("Activity Cube Baby 6-in-1",        "Shape sorter, bead maze, spinning wheels.",            1299.00, True),
        ("Pull-Along Toy Duck Wooden",       "String pull wooden duck with quacking bead.",           499.00, True),
        ("Toy Tool Set 20pc",                "Role-play tool kit with drill, saw, and bolts.",        799.00, True),
        ("Dinosaur Figurines Set 12pc",      "Realistic hand-painted dinosaur figures.",              999.00, True),
        ("My First Coding Robot",            "Screen-free coding robot for ages 3–6.",              3499.00, True),
        ("Science Experiment Kit 50",        "50 STEM science experiments with manual.",             1999.00, True),
        ("Astronomy Kit Telescope",          "20×–70× tabletop refracting telescope for kids.",     2499.00, True),
        ("Magnetic Tiles 80pc",              "STEM magnetic building tiles, transparent.",           3999.00, True),
        ("Human Body Model 3D",              "Removable organs anatomy model, 31 cm.",              1499.00, True),
        ("Crystal Growing Kit",             "Grow 6 crystals in 24 hours, safe chemicals.",          799.00, True),
        ("Fingerprint Chemistry Set",        "Forensic science kit with real fingerprint dust.",     1299.00, True),
        ("Remote Control Helicopter",        "3.5ch indoor RC helicopter, gyro stabilised.",        2999.00, True),
        ("Toy Cash Register Electronic",     "Play register with scanner and play money.",           1299.00, True),
        ("Mini Pocket Chess Magnetic",       "Foldable magnetic travel chess, 19 cm.",              699.00, True),
        ("Balancing Cactus Game",            "Stacking and balancing skill game for kids.",          599.00, True),
        ("Giant Snakes and Ladders",         "Floor-size 100-square printed mat game.",             1499.00, True),
        ("Bubble Machine Automatic",         "Automatic bubble machine with 500ml solution.",        999.00, True),
        ("Kite Delta Nylon 1.5m",            "Easy-fly delta kite with 50m string.",                699.00, True),
        ("Board Game Storage Insert",        "Foam-core universal organiser for game boxes.",        999.00, True),
        ("Tabletop Foosball Mini",           "Countertop 2-player foosball game.",                  2499.00, True),
        ("Drone for Kids Indoor",            "Hand-sensor hover drone, LED lights, age 8+.",        1999.00, True),
        ("Walkie Talkies Kids 8km",          "PMR 8km range, weather-alert, belt clip.",            1499.00, True),
        ("Card Game Dobble 55 Cards",        "Fast-paced spot-the-symbol game, 2–8 players.",       799.00, True),
        ("Puppet Theatre Fabric Frame",      "Tabletop puppet stage with 4 hand puppets.",          1799.00, True),
        ("Toy Kitchen Playset 45pc",         "Wooden kitchen with sounds + accessories.",           3999.00, True),
        ("Doll House Wooden 4-Floor",        "6-room wooden dollhouse with furniture.",             7999.00, True),
        ("Model Train Set Oval Track",       "Electric oval train set, 4 m of track.",             4999.00, True),
        ("Kaleidoscope Wooden Toy",          "Rotating mirror kaleidoscope, 22 cm.",               699.00, True),
    ],

    "Health & Wellness": [
        ("Digital BP Monitor Wrist",         "Irregular heartbeat detection, 60-reading memory.",   1999.00, True),
        ("Pulse Oximeter Fingertip",         "SpO2 + PR + PI, OLED display, AAA batteries.",        799.00, True),
        ("Glucometer Complete Kit",          "25 strips, lancing device, control solution.",        1499.00, True),
        ("Digital Thermometer Infrared",     "1-sec forehead/ear reading, fever alert.",            999.00, True),
        ("Nebuliser Compressor",             "Compressed air nebuliser, 0.3 µm particle.",         2499.00, True),
        ("TENS Unit Dual Channel",           "8-mode TENS machine with 12 pads.",                  1999.00, True),
        ("Heating Pad Electric 40×50cm",     "6 heat settings, auto-off, washable cover.",         1299.00, True),
        ("Hot Water Bottle 2L",              "Ribbed rubber bottle with fleece cover.",             499.00, True),
        ("Acupressure Mat + Pillow Set",     "Lotus spike mat for back pain relief.",              1299.00, True),
        ("Melatonin Sleep Mask Heated",      "USB heated eye mask with timer.",                    1199.00, True),
        ("Air Purifier HEPA H13 25m²",       "True HEPA + activated carbon, CADR 230.",           6999.00, True),
        ("Humidifier Ultrasonic 4L",         "Cool mist, sleep mode, auto-off, 360° nozzle.",     2499.00, True),
        ("Himalayan Salt Lamp 2–3kg",        "Natural amber salt lamp with dimmer switch.",        1299.00, True),
        ("Massage Gun Percussive",           "2400 RPM, 6 heads, 5 speeds, 2500 mAh.",            3999.00, True),
        ("Foam Roller Vibrating 4-Speed",    "4-speed vibrating foam roller, USB-C.",              3499.00, True),
        ("Posture Corrector Adjustable",     "Figure-8 strap for back and shoulder support.",      799.00, True),
        ("Knee Brace Hinged",                "Adjustable hinged knee stabiliser brace.",            999.00, True),
        ("Wrist Splint Carpal Tunnel",       "Rigid palmer plate wrist splint.",                   799.00, True),
        ("Lumbar Support Cushion",           "Memory foam lumbar pillow with car/chair strap.",    999.00, True),
        ("Cervical Neck Pillow Memory",      "Ergonomic contour memory foam travel pillow.",       1299.00, True),
        ("Wheatgrass Powder 500g",           "USDA organic wheatgrass, cold-pressed.",              899.00, True),
        ("Ashwagandha 500mg 60 Caps",        "KSM-66 full-spectrum root extract.",                  799.00, True),
        ("Omega-3 Fish Oil 1000mg 90s",      "Molecularly distilled, enteric coated.",              699.00, True),
        ("Multivitamin Complete 60 Tabs",    "22 vitamins & minerals, time-release.",               799.00, True),
        ("Magnesium Glycinate 400mg",        "High-absorption chelated magnesium.",                 699.00, True),
        ("Probiotic 50B CFU 30 Caps",        "10-strain probiotic, acid-resistant capsule.",        999.00, True),
        ("Collagen Peptides Powder 300g",    "Hydrolysed bovine collagen types I & III.",          1299.00, True),
        ("Spirulina Tablets 500mg 250pc",    "Organic spirulina, cold-processed.",                  799.00, True),
        ("Vitamin D3 5000 IU 120 Soft",      "Cholecalciferol with organic olive oil.",             599.00, True),
        ("Zinc Bisglycinate 25mg 60s",       "Chelated zinc for immune support.",                  499.00, True),
        ("Neti Pot Ceramic 300ml",           "Traditional ceramic nasal rinse pot.",               499.00, True),
        ("Eye Drops Lubricating 10ml",       "Carboxymethylcellulose dry-eye drops.",              299.00, True),
        ("First Aid Kit 200pc Traveller",    "Comprehensive kit with bandages, antiseptics.",      1299.00, True),
        ("Hand Sanitiser Gel 500ml",         "70% ethanol gel with aloe vera.",                    299.00, True),
        ("Medical Compression Stocking",     "18–21 mmHg graduated knee-high pair.",               799.00, True),
        ("Melatonin 5mg 60 Tablets",         "Fast-dissolve sleep support tablets.",               499.00, True),
        ("Portable Saline Nasal Spray",      "Isotonic nasal saline, 100 ml.",                    299.00, True),
        ("Resistance Band Stretch Physio",   "Latex-free therapy band for rehab.",                 399.00, True),
        ("Aromatherapy Diffuser 500ml",      "Ultrasonic oil diffuser, 7 LED colours.",           1499.00, True),
        ("Bamboo Tongue Depressor 100pc",    "Medical-grade birch wood sticks.",                   199.00, True),
        ("Cold Therapy Ice Pack Wrap",       "Reusable gel pack with flexible wrap.",              699.00, True),
        ("Blood Glucose Test Strips 50pc",   "Compatible with common glucometers.",               799.00, True),
        ("UV Steriliser Box 15L",            "99.9% UVC-LED steriliser for devices.",            3499.00, True),
        ("Meditation Cushion Buckwheat",     "Round zafu, organic buckwheat hull fill.",          1499.00, True),
        ("Ergonomic Seat Cushion Coccyx",    "Memory foam coccyx relief cushion.",               999.00, True),
        ("Resistance Putty Therapy 3pc",     "Soft/medium/firm silicone putty for hand rehab.",  599.00, True),
        ("Wearable Pain Relief Patch 30pc",  "Methyl salicylate heat patches, 8h relief.",       699.00, True),
        ("CPR Face Shield Keyring",          "Compact CPR one-way valve mask.",                   299.00, True),
        ("Pulse Timer for Meditation",       "LED pulse timer with 7 interval settings.",         799.00, True),
        ("Trigger Point Ball Set 3pc",       "Lacrosse-size massage balls in 3 densities.",      799.00, True),
    ],

    "Automotive": [
        ("Car Dash Cam 4K Front+Rear",       "4K front + 1080p rear, built-in GPS, Wi-Fi.",      5999.00, True),
        ("Tyre Inflator Portable 150PSI",    "Digital preset, auto-stop, 12V/USB-C.",            1999.00, True),
        ("Jump Starter 2000A Peak",          "LiFePO4 pack, USB-A 18W, LED torch.",              4999.00, True),
        ("Car Vacuum Cleaner 12V 120W",      "Wet/dry, HEPA filter, 5 m cable.",                1499.00, True),
        ("Windshield Sunshade Foldable",     "Reflective accordion sunshade, 150×80 cm.",         799.00, True),
        ("Car Phone Mount Magnetic",         "Qi wireless charging magnetic vent mount.",          999.00, True),
        ("OBD2 Bluetooth Scanner ELM327",    "Real-time diagnostics, iOS & Android.",             999.00, True),
        ("Car Seat Covers Universal",        "5-piece PU leather set, airbag-compatible.",       2999.00, True),
        ("Steering Wheel Cover Leather",     "Genuine leather cover, 37–39 cm diameter.",         799.00, True),
        ("Car Air Freshener Vent Clip",      "Aromatherapy vent diffuser, 5 scents.",             349.00, True),
        ("Wiper Blades 24+16in Pair",        "Beam-style frameless wipers, all-weather.",         799.00, True),
        ("Reversing Camera 170° HD",         "Night-vision backup camera, universal fit.",        1299.00, True),
        ("Car Cover SUV Waterproof",         "7-layer outdoor cover for large SUVs.",            2999.00, True),
        ("Floor Mats Rubber 4pc",            "All-weather heavy-duty rubber mat set.",            1499.00, True),
        ("Tyre Pressure Gauge Digital",      "0–100 PSI digital gauge with LED.",                 499.00, True),
        ("Roof Rack Crossbars Universal",    "Adjustable aluminium crossbar pair.",              3499.00, True),
        ("Car Trash Can Lid 8L",             "Leak-proof bin with lid, headrest mount.",          599.00, True),
        ("Garage Parking Sensor 4-Piece",    "Reverse ultrasonic sensor with buzzer.",           1299.00, True),
        ("Car Organiser Boot 35L",           "Collapsible trunk organiser with dividers.",        999.00, True),
        ("Emergency Road Kit 26pc",          "Reflective triangles, jumper cables, torch.",      1999.00, True),
        ("Leather Dashboard Conditioner",    "UV-guard conditioning spray for dashboards.",       699.00, True),
        ("Clay Bar Detailing Kit",           "Clay + lubricant + microfibre for paintwork.",     1199.00, True),
        ("Foam Cannon Pressure Washer",      "1/4in QC foam cannon, 1L bottle.",                 1499.00, True),
        ("Microfibre Towels Car 10pc",       "380 GSM dual-weave detailing towels.",              899.00, True),
        ("Tyre Shine Spray 500ml",           "Wet-look tyre dressing, long-lasting.",             499.00, True),
        ("Scratch Remover Pen",              "Waterproof touch-up pen for car scratches.",        699.00, True),
        ("Car Polish Compound 500ml",        "One-step oxidation remover and polish.",             999.00, True),
        ("Seat Gap Organiser Leather",       "Dual seat gap filler and storage pouch.",           599.00, True),
        ("Tow Rope Braided 5m 8T",           "8-tonne rated recovery tow rope.",                 1299.00, True),
        ("Seat Belt Extender 30cm",          "3-inch wide E-mark approved extender.",             599.00, True),
        ("Car Battery Tender 1.25A",         "Float charger/maintainer for 12V batteries.",     1999.00, True),
        ("LED Interior Strip 4pc",           "RGB USB-powered LED strips with remote.",           799.00, True),
        ("Window Tint Film 5% VLT",          "Pre-cut 100×50cm self-adhesive film.",              599.00, True),
        ("Car First Aid Kit 45pc",           "EN 13164 compliant road first aid kit.",            999.00, True),
        ("Magnetic Tow Hitch Step",          "Magnetic retractable step for tow hitch.",         2499.00, True),
        ("Ski/Snowboard Roof Box 340L",      "340 L aerodynamic roof box.",                      9999.00, False),
        ("Folding Trunk Ramp 2pc Aluminium", "300 kg-rated aluminium loading ramp pair.",        3999.00, True),
        ("EV Portable Charger Type 2 7.4kW", "Portable 32A Type 2 EV charger, 5 m cable.",    12999.00, True),
        ("Car Blind Spot Mirror 2pc",        "Convex wide-angle side mirror stickers.",           299.00, True),
        ("Gear Shift Knob Leather",          "M10×1.5 universal leather gear knob.",              799.00, True),
        ("Trunk Mat Waterproof Custom",      "Heavy-duty tailored boot liner mat.",              1499.00, True),
        ("AC Vent Freshener Bamboo Charcoal","Activated charcoal odour eliminator, 2pc.",        399.00, True),
        ("Car Polisher DA Orbital 900W",     "Dual-action polisher with 5 pad set.",            4999.00, True),
        ("Fuel Injector Cleaner Additive",   "200 ml petrol/diesel injector cleaner.",           499.00, True),
        ("Tyre Repair Kit Sealant 450ml",    "Tubeless tyre inflator + sealant.",                799.00, True),
        ("Rear Seat Entertainment",          "10in HD headrest monitor with HDMI + USB.",       5999.00, True),
        ("Anti-Theft Steering Lock",         "Heavy-duty steering wheel bar lock.",             1299.00, True),
        ("Seat Heater Pad 12V",              "3-level heating pad for car seat, 12V.",           999.00, True),
        ("Alloy Wheel Touch-Up Paint",       "Multi-shade metallic touch-up spray.",             699.00, True),
        ("Car Document Organiser Wallet",    "Leather wallet for insurance, RC, & permit.",      399.00, True),
    ],
}


class Command(BaseCommand):
    help = "Seed the database with 10 categories × 50 products = 500 products."

    def handle(self, *args, **options):
        self.stdout.write("Starting seed …")

        categories_created  = 0
        products_created    = 0

        with transaction.atomic():
            for cat_name, products in SEED_DATA.items():
                category, created = Category.objects.get_or_create(name=cat_name)
                if created:
                    categories_created += 1
                    self.stdout.write(f"  ✔ Category created : {cat_name}")
                else:
                    self.stdout.write(f"  – Category exists  : {cat_name}")

                for (prod_name, description, price, is_available) in products:
                    _, p_created = Product.objects.get_or_create(
                        name=prod_name,
                        category=category,
                        defaults={
                            "description":   description,
                            "price":         Decimal(str(price)),
                            "is_available":  is_available,
                        }
                    )
                    if p_created:
                        products_created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"\nDone! {categories_created} categories and "
                f"{products_created} products inserted."
            )
        )